# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Test pod lint and Build carthage"
  lane :test do
    test_lib
    pod_lint
  end

  desc "Cocoapods lint the pod for all platforms"
  private_lane :pod_lint do
    pod_lib_lint(allow_warnings: true)
  end

  desc "Run the tests"
  private_lane :test_lib do  
    scan(workspace: "RxAlertExample.xcworkspace",
         scheme: "RxAlertExample"
        )
  end

  desc "Carthage Build"
  lane :carthage_build do
    carthage(
      command: "build",
      use_ssh: false,
      use_submodules: false,
      use_binaries: true,
      no_build: false,
      no_skip_current: true,
      verbose: false,
      platform: "all",
      configuration: "Release",
      cache_builds: false,
      toolchain: "com.apple.dt.toolchain.Swift_4",
      new_resolver: false,
      log_path: "carthage.log"
    )
  end
end
